definitions:
  Request:
    properties:
      headers:
        additionalProperties:
          type: string
        example:
          Authorization: Bearer token
          Content-Type: application/json
        type: object
      method:
        example: GET
        type: string
      url:
        example: http://google.com
        type: string
    required:
    - headers
    - method
    - url
    type: object
  Response:
    properties:
      headers:
        additionalProperties:
          type: string
        example:
          Content-Type: application/json
        type: object
      id:
        example: "1"
        type: string
      length:
        example: 100
        type: integer
      status:
        example: 200
        type: integer
    type: object
info:
  contact: {}
paths:
  /proxy:
    post:
      consumes:
      - application/json
      description: Proxy client request
      parameters:
      - description: Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Response'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Proxy client request
      tags:
      - Proxy
swagger: "2.0"
